### ISSUE TITLE
With Jasmine 2, all tests fail with "undefined is not a function"

### ISSUE THREAD

**Issue by patreeceeo** [goodeggs/jasmine-bail-fast#1]
Perhaps there should be a warning that Jasmine 2 isn't supported, or it should be documented? 

```
Stack:
    TypeError: undefined is not a function
        at Object.<anonymous> (/path/to/codes/node_modules/jasmine-bail-fast/jasmine-bail-fast.js:4:15)
        at Array.forEach (native)
        at runMicrotasksCallback (node.js:337:7)
        at process._tickCallback (node.js:355:11)
```

**Comment by M0ns1gn0r** [comment]
Exactly, or even better a line in the README.

**Comment by F1LT3R** [comment]
+1 to making this clearer

**Comment by prakashkrishnan1985** [comment]
I'm getting an error  - TypeError: this.results is not a function. Any idea why this is happening?

**Comment by metrophos** [comment]
Here is my solution to skip tests on first fail with jasmine2.
I use it for my protractor tests. Hope it helps.

```
            //skip tests after first fail
            var specs = [];
            var orgSpecFilter = jasmine.getEnv().specFilter;
            jasmine.getEnv().specFilter = function(spec) {
                specs.push(spec);
                return orgSpecFilter(spec);
            };
            jasmine.getEnv().addReporter(new function () {
                this.specDone = function (result) {
                    if (result.failedExpectations.length > 0) {
                        specs.forEach(function (spec) {
                            spec.disable()
                        });
                    }
                };
            });
```
